name: hearai
description: "hearai"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.1
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.12.0
  ionicons: ^0.2.2
  dio: ^5.9.0
  json_annotation: ^4.9.0
  crypto: ^3.0.7
  device_info_plus: ^12.2.0
  ed25519_edwards: ^0.3.1
  flutter_secure_storage: ^9.2.4
  audioplayers: ^6.5.1
  webview_flutter: ^4.13.0
  google_fonts: ^6.3.2
  awesome_dialog: ^3.3.0
  intl: ^0.20.2
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  wechat_kit: ^6.0.2
  flutter_dotenv: ^6.0.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  json_serializable: ^6.11.3
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - .env.prod

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/logo_960.png"

wechat_kit:
  app_id: wxb76a447bb568b5d8
  universal_link: https://xxxxx.com/universal_link/example_app/wechat/
